<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Intel.RealSense">
      <HintPath>..\..\..\LIB\librealsense\build\Release\Intel.RealSense.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>